sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 185029033
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSr839Hk5Ze71HNut7e
    access-key-secret: rEEk3ZPSCnDCzRhl6OGY2GqdbvBaV2
    bucket-name: sky-itcast-wyj
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wexin:
    appid: wxd88e123792fa067b
    secret: bade8560cc75d40675669cc97ddd112c