sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 185029033
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSr839Hk5Ze71HNut7e
    access-key-secret: rEEk3ZPSCnDCzRhl6OGY2GqdbvBaV2
    bucket-name: sky-itcast-wyj
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wexin:
    appid: wxd88e123792fa067b
    secret: bade8560cc75d40675669cc97ddd112c
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess